# Dev config
server:
  port: 8080
  servlet:
    context-path: /dhshop
spring:
  datasource:
    url: jdbc:h2:~/dhshopdb
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      fail-on-empty-beans: false
      
swagger2:
  base-package: vn.dhteams.service.onlineshop.controller
  auth-service: http://localhost:8080/dhshop